#Maven Build--------------------------------------------------------
java: 1.8
akmid: 102861
maven: apache-maven-3.3.9
appVersion: 0.1
pomFileLocation: 'pom.xml'
mavenGoals: clean install -Dbranch=master
